import Head from "next/head";
import { Inter } from "next/font/google";
import HomeMainContent from "@/components/homeMainContent";
import HomeSideContent from "@/components/HomeSideContent";

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>HomePage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section
        className={`flex  flex-col lg:flex-row md:flex-row sm:flex-col justify-center py-10 min-h-screen bg-white gap-4 `}
      >
        <HomeMainContent dataPost={data} />
        <div className="border-l-2 border-gray-400 "></div>
        <HomeSideContent />
      </section>
      <section></section>
    </>
  );
}

export async function getServerSideProps(ctx) {
  const res = await fetch(`http://localhost:3000/api/artikels`);
  const data = await res.json();

  return { props: { data } };
}
