import Head from "next/head";
import LoginFormCard from "@/components/loginPage/LoginFormCard";

const Login = () => {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-primaryTheme absolute top-0 left-0 bg-gradient-to-b from-gray-900 via-gray-900 to-primaryTheme bottom-0 leading-5 h-min p-5 w-full">
        <div className="relative min-h-0 md:min-h-screen sm:flex sm:flex-row justify-center bg-transparent rounded-3xl shadow-xl p-10">
          <div className=" flex-col flex self-center lg:pr-14 sm:max-w-4xl xl:max-w-md z-10">
            <div className="self-start hidden lg:flex flex-col  text-gray-300">
              <h1 className="my-3 font-semibold text-4xl">Welcome back</h1>
              <p className="pr-3 text-sm opacity-75">
                Lorem ipsum is placeholder text commonly used in the graphic,
                print, and publishing industries for previewing layouts and
                visual mockups
              </p>
            </div>
          </div>
          <LoginFormCard />
        </div>
      </div>
    </>
  );
};

export default Login;
