import { useState } from "react";
import Sidebar from "@/components/dashboard/sideBar";
import MenuBarMobile from "@/components/dashboard/menuBarMobile";
import Head from "next/head";
import ManageBlogPost from "@/components/dashboard/manageBlogPost";
import ManageUser from "@/components/dashboard/manageUser";
import DashboarEditor from "@/components/dashboard/dashboardEditor";
import { useRouter } from "next/router";

const Dashboard = ({ posts }) => {
  const router = useRouter();

  const [showSidebar, setShowSidebar] = useState(false);
  const [children, setChildren] = useState("blogPost");
  // console.log(router);

  return (
    <>
      <Head>
        <title>Admin Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-gray-300 rounded-t-2xl">
        <div className="flex">
          <MenuBarMobile setter={setShowSidebar} />
          <Sidebar
            child={setChildren}
            show={showSidebar}
            setter={setShowSidebar}
          />
          <div className="p-0 md:px-5 md:py-6 flex flex-col flex-grow w-screen md:w-full min-h-screen">
            {children === "blogPost" ? <ManageBlogPost posts={posts} /> : <></>}
            {children === "manageUser" ? <ManageUser /> : <></>}
            {children === "editor" ? <DashboarEditor /> : <></>}
          </div>
        </div>
      </div>
    </>
  );
};

export async function getStaticProps() {
  const res = await fetch("http://localhost:3000/api/artikels");
  const posts = await res.json();
  // console.log(posts);

  return {
    props: {
      posts,
    },
    revalidate: 10,
  };
}

export default Dashboard;
